config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :tweets, only: :create

  get :dashboard, to: "dashboard#index"

  resources :usernames, only: [:new, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: { case_sensitive: false }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :redirect_to_username_form, if: -> { user_signed_in? && current_user.username.blank? }
    protected

    def after_sign_in_path_for(resource)
        dashboard_path
    end

    def redirect_to_username_form
        redirect_to new_username_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to dashboard_path if user_signed_in?
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :authenticate_user!
	def create
		tweet = Tweet.new(tweet_params.merge(user: current_user))

		if tweet.save
				redirect_to dashboard_path
		end
	end

	private

	def tweet_params
		params.require(:tweet).permit(:body)
	end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
	before_action :authenticate_user!
	skip_before_action :redirect_to_username_form

	def new
	end

	def update
		if username_params[:username].present? && current_user.update(username_params)
			flash[:notice] = "Username successfully updated"
			redirect_to dashboard_path
		else
			flash[:alert] = username_params[:username].blank? ? "Please set a username" : current_user.errors.full_messages.join(", ")
			redirect_to new_username_path
		end
	end

	private

	def username_params
		params.require(:user).permit(:username)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>We are logged in!</h1>
<%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "btn btn-primary btn-lg" %>

<%= form_with model: Tweet.new, url: tweets_path, method: :post, local: true do |f| %>
    <%= f.text_field :body %>
    <%= f.submit %>
<% end %>

<ul>
    <%= Tweet.find_each do |tweet | %>
        <li><%= tweet.user.username %> | <%= tweet.body %></li>
    <% end %>
</ul>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Log in", new_user_session_path, class: "btn btn-outline-primary btn-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if flash.any? %>
      <%= render "shared/flashes" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/usernames/new.html.erb
<div class="container py-5" style="max-width: 540px">
  <h2>Set your username</h2>
    <%= form_with model: current_user, local: true, url: username_path(current_user) do |f| %>
			<div class="mb-3">
				<%= f.label :username, class: "form-label" %>
				<%= f.text_field :username, class: "form-control" %>
			</div>
			<%= f.submit "Set username", class: "btn btn-primary" %>
    <% end %>
</div>